name = "franklin-figma"
main = "dist/index.mjs"

account_id = "b4adf6cfdac0918eb6aa5ad033da0747"
workers_dev = true

compatibility_date = "2022-06-13"
compatibility_flags = []
kv_namespaces = [
  { binding = "SESSIONS", id = "0173b103f3814969b2bece9f00fb6622", preview_id = "0173b103f3814969b2bece9f00fb6622" }
]

[build]
command = "NODE_ENV=development npm run build"
watch_dir = "./src"


[env.stage]
kv_namespaces = [
  { binding = "SESSIONS", id = "0173b103f3814969b2bece9f00fb6622", preview_id = "0173b103f3814969b2bece9f00fb6622" }
]

[env.stage.build]
command = "NODE_ENV=stage npm run build"


[env.production]
kv_namespaces = [
  { binding = "SESSIONS", id = "0173b103f3814969b2bece9f00fb6622", preview_id = "0173b103f3814969b2bece9f00fb6622" }
]

[env.production.build]
command = "NODE_ENV=production npm run build"


[vars]
MICROSOFT_CLIENT_ID = "86991aa5-bcf3-4799-a3c4-498871fe112d"
GOOGLE_CLIENT_ID = "995105859161-3qnj51u0ui5pu9bj5pa1p2o9ga24ej2k.apps.googleusercontent.com"
ENDPOINT = "http://localhost:3001"
UPSTREAM = "http://localhost:3000"

[env.stage.vars]
MICROSOFT_CLIENT_ID = "86991aa5-bcf3-4799-a3c4-498871fe112d"
GOOGLE_CLIENT_ID = "995105859161-3qnj51u0ui5pu9bj5pa1p2o9ga24ej2k.apps.googleusercontent.com"
ENDPOINT = "https://figma.helix3.dev"
UPSTREAM = "https://main--franklin-figma--maxakuru.hlx.page"

[env.production.vars]
MICROSOFT_CLIENT_ID = "86991aa5-bcf3-4799-a3c4-498871fe112d"
GOOGLE_CLIENT_ID = "995105859161-3qnj51u0ui5pu9bj5pa1p2o9ga24ej2k.apps.googleusercontent.com"
ENDPOINT = "https://figma.helix3.dev"
UPSTREAM = "https://main--franklin-figma--maxakuru.hlx.page"


# The necessary secrets are:
# - GOOGLE_CLIENT_SECRET
# - GOOGLE_DEVICECODE_CLIENT_SECRET
# - MICROSOFT_CLIENT_SECRET
# - GOOGLE_API_KEY
# Run `wrangler secret put <NAME> --env <production|stage>` for each of these